deps/crc32/crc32.c
For windows support, we want to send patches separately.
This patch fixes `<endian.h>` not found on Windows.
=> crc32: Fix function definitions on WIN32

include/chunkio/chunkio_compat.h, include/chunkio/cio_chunk.h, include/chunkio/cio_os.h, src/chunkio.c, src/cio_chunk.c, src/cio_file.c, src/cio_memfs.c, src/cio_os.c, src/cio_stream.c, src/cio_utils.c, tools/cio.c
Windows does not have `<unistd.h>`.
When using `#ifdef _WIN32` macro simply, it makes flood of `#ifdef _WIN32`.
Then, we should create compat layer and use it.
=> Introduce Windows compat layer

CMakeLists.txt
Because MSVC does not recognize `-Wall` and `-fPIC` compiler options.
Instead, we should use `set(CMAKE_POSITION_INDEPENDENT_CODE ON)` and `/Wall` instead of `-Wall`.
Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>
=> build: Adjust CFLAGS for MSVC

CMakeLists.txt, src/CMakeLists.txt, src/cio_chunk.c, src/cio_meta.c, src/cio_scan.c, tests/CMakeLists.txt
This PR is one of the related tasks for https://github.com/fluent/fluent-bit/issues/960.
---
When `CIO_BACKEND_FILESYSTEM=off`(in-memory mode), chunkio relies on `malloc`.
This change makes easier to port Windows environment.
BTW, in Windows, we also must port directory related API and remove `unistd.h` and other Linux dependent headers usages. I'll try it out later.
~~The above task is progressing on #3.~~ Done. :tada:
=> Add CIO_BACKEND_FILESYSTEM=On/Off to enable/disable filesystem backend support. 

tools/cio.c
Right now, running `tools/cio` instantly fails with SIGSEGV:
$ echo test | tools/cio -i -s stdin -v -r cio
[cio] caught signal (SIGSEGV)
Aborted
Evidently this is caused by b204911 that has modified the log function
interface, but forgot to update the implementation in `tools/cio.c`.
Part of https://github.com/fluent/fluent-bit/issues/960
=> tools: cio: fix SIGSEGV due to incompatible argument types

tests/fs.c, tests/memfs.c
This fixes the function prototype of the logging function in the
test programs.
With this patch applied, I can confirm all test cases go green on
Linux.
Part of https://github.com/fluent/fluent-bit/issues/960
=> tests: fix SIGSEGV in 'cio-test-fs' and 'cio-test-memfs'

tools/cio.c
This patch syncs the help message with the actual command-line options.
For example, `-f` was incorrectly described to take an integer as
its argument. With this patch these errors should be all cleared away.
Signed-off-by: Fujimoto Seiji <fujimoto@clear-code.com>
=> tools: cio: fix up the description of the command line options

include/chunkio/cio_chunk.h
On Linux, <sys/types.h> seems to be included indirectly though some
other headers. However, on Windows it doesn't.
This causes the compilation to fail on MSVC with "unknown type off_t"
errors.
Main issue link: https://github.com/fluent/fluent-bit/issues/960
=> chunk: include <sys/types.h> explicitly

include/chunkio/chunkio_compat.h
This PR attempts to clean up the compatibility layer for Windows.
e970b08 compat: clean up the compatibility stuffs for Windows
7097022 compat: fix the compat implementation of dirname()
Part of https://github.com/fluent/fluent-bit/issues/960
=> compat: clean up the compatibility definitions for Windows

include/chunkio/cio_chunk.h, include/chunkio/cio_os.h, src/chunkio.c, src/cio_chunk.c, src/cio_file.c, src/cio_log.c, src/cio_memfs.c, src/cio_os.c, src/cio_utils.c
Previously, chunkio exposed functions and macros in chunk_compat.h
as part of library interface. This caused a number of issues in the
downstream source code (e.g. conflicts of macro definitions).
This patch prevents the compatibility header from leaking to the
outer world, while keeping the source tree compilable.
Part of https://github.com/fluent/fluent-bit/issues/960
=> compat: do not expose chunk_compat.h as part of library interface

include/chunkio/cio_os.h
We need this in order to compile the source code on Alpine 3.8.2.
Since mode_t is defined in <sys/types.h> on UNIX systems, we need
to include the header before using it.
Should fix the issue fluent/fluent-bit/issues/1011
=> os: include <sys/types.h> for mode_t

include/chunkio/chunkio_compat.h, src/cio_file.c, src/cio_os.c, src/cio_scan.c
Instead of adding ifdefs to each source file, we can aggregate the
non-portable headers in the compat header.
This patch accumulate libgen.h, dirent.h and arpa/inet.h, which are
not available on Windows.
=> compat: accumulate platform dependent headers

src/cio_scan.c
cio_scan_stream() is essentially a function to read chunks from file
storage, and heavily relies on non-portable file system functions
(namely dirent.h).
We need to mock this function out in order to compile the source tree
on platforms without file system backend (i.e. Windows).
=> scan: stub out cio_scan_streams() if file system backend is disabled

include/chunkio/cio_file.h, src/cio_file.c, src/cio_file_compat.c, src/cio_meta.c
Previously, cio_meta_write() contained a lot of filesystem specific
codes and was hard to support CIO_HAVE_BACKEND_FILESYSTEM=Off.
This patch separates out filesystem-dependant stuffs cleanly, and at the
same time enables us to compile cio_meta.c on Windows (VC++) nicely.
NOTE: This patch just moves a chunk of codes, involiving no actual
change to the logic.
=> meta: move the file writer into a separate function

src/cio_utils.c, tools/cio.c
The basic idea is that we can make `cio_utils_read_file()` usable on
Windows by replacing mmap with fread/calloc.
NOTE: Since the function doesn't rely on mmap anymore, the caller
must call free (instead of munmap) to reclaim the memory. This
patch also takes care of it.
=> utils: use fread(3) to read the content of file into memory buffer

tools/cio.c
Since most Windows consoles do not understand ANSI escapes, we need
to disable it to prevent the output from being corrupted.
Note: This is essentially the same change set with monkey/monkey/pull/289.
=> tools: disable ANSI color escapes on Windows

tools/cio.c
CIO_PERF_PATH is essencially `root_path` for perf testing, and we do
not need to initialize it if we choose to use memory backend.
This patch allows us to run the perf testing on custom builds without
the filesystem backend support.
$ ./tools/cio -M -p test.dat
=> tools: do not initialize CIO_PERF_PATH when we use memory backend

src/cio_utils.c
We do not need to compile this function on MSVC, since Windows does
not have the filesystem backend support yet.
In future, when we add the filesytem support to Windows, we'll need
to implement the functionality using Win32 API.
=> utils: stub out cio_utils_recursive_delete() on Windows

src/cio_utils.c
This patch allows us to compile `cio_utils.c` on Windows without
"no such header file found" errors.
This patch needs merging after #25 and #28.
=> utils: do not include headers if not necessary

include/chunkio/chunkio_compat.h
We need this in order to avoid conflict of functions symbols
in the downstream programs.
=> compat: add missing "static" declaration for getpagesize()

CMakeLists.txt
... so that we can build chunkio on Windows just by:
$ cd build
$ cmake ..
$ make
Without this, we need to not forget to add a special option
-DCIO_BACKEND_FILESYSTEMA=Off to the second line.
=> build: turn off CIO_BACKEND_FILESYSTEM on Windows

include/chunkio/cio_file.h, src/cio_file_compat.c
The following file function interfaces were added in 349752a.
- cio_file_up()
- cio_file_down()
- cio_file_is_up()
This patch adds corresponding implementations to cio_file_compat.h.
The main effect of this patch is getting chunkio compilable on Windows.
Also I cleaned up a non-existing function from cio_file.h in 5b755d1,
in order to make every bit in sync perfectly.
=> file: make chunkio compilable again on Windows

src/cio_file_compat.c
We need this in order to compile the module on Windows without an
error about unresolved symbols.
This should bring chunkio to Windows-ready again.
Signed-off-by: Fujimoto Seiji <fujimoto@clear-code.com>
=> file_compat: add stub function for cio_file_up_force()

src/cio_stats.c
This is a simple fix to make cio_stats.c compilable on Windows.
In short, it needs chunkio_compat.h to load a chain of Windows-
specific headers.
Signed-off-by: Fujimoto Seiji <fujimoto@clear-code.com>
=> stats: make it compatible with Windows

include/chunkio/chunkio.h, include/chunkio/cio_log.h, src/chunkio.c, tests/context.c
I added a trace level to logger.
I encountered the following error  when I tried [README example about cio]( https://github.com/edsiper/chunkio/blob/f68c66364a4ee87723203ac09ea2580681e21b53/README.md#cio---client-tool).
```
$ cat ./CMakeCache.txt | tools/cio -i -s stdin -f somefile -vvv                                                                                    
[cio] invalid log level, aborting
```
I found it was caused by [this commit](https://github.com/edsiper/chunkio/commit/24791539a498aa8d6ce22d678d679618c859d8ef#diff-c7299ab194b49468d1a3b7c86599d91cR397).  and I also found cio didn't have trace log level.
If you don't like adding trace level, I will change this PR to removing `v` from `-vvv` in README.
@edsiper what do you think of this pr?
=> Add trace level log

CMakeLists.txt, src/cio_file.c
(via [fluent-bit](https://github.com/fluent/fluent-bit/pull/1452))
Some versions of uClibc don't have fallocate, eventhough Linux of a sort.
This change adds a cmake check for fallocate.
=> file: cmake check for fallocate availability

src/cio_file.c
Current implementation occurs the following error when loading file is an invalid format.
this cause is calling `cio_file_close` twice at and
https://github.com/edsiper/chunkio/blob/1452f4175d808a855c80d3f93ae83383a4b8cd90/src/cio_file.c#L330
and
https://github.com/edsiper/chunkio/blob/1452f4175d808a855c80d3f93ae83383a4b8cd90/src/cio_file.c#L525
```
cio(86087,0x1054265c0) malloc: *** error for object 0x7fea3ac02d60: pointer being freed was not allocated
cio(86087,0x1054265c0) malloc: *** set a breakpoint in malloc_error_break to debug
```
minimal reproduction code
```c
struct cio_ctx *ctx;
struct cio_stream *stream;
ctx = cio_create("tmp", 0, CIO_DEBUG, 0);
stream = cio_stream_create(ctx, "test", CIO_STORE_FS);
cio_chunk_open(ctx, stream, "c", CIO_OPEN, 1000);
```
tmp/test/c
```
{}
```
=> ensure call cio_file_close in mmap_file to avoid double free

src/cio_file_compat.c
Without this, we cannot link chunkio on Windows.
unresolved external symbol cio_file_content_copy
Resolve this issue by adding a compatibility shim function.
Note: This commit is required to compile Fuent Bit v1.6.0.
Signed-off-by: Fujimoto Seiji <fujimoto@clear-code.com>
=> file_compat: add stub function for cio_file_copy_content()

include/chunkio/cio_file.h
`cio_file_close_stream()` is a ghost function that does not have
a corresponding implementation in `cio_file.c`.
This patch removes the declaration from the header file.
=> file: Remove a non-existent function 'cio_file_close_stream()'

include/chunkio/chunkio.h
`cio_chunk_get_real_size()` has two prototype declarations:
(1) line 70 in chunkio/chunkio.h
(2) line 50 in chunkio/cio_chunk.h.
This patch removes (1) to avoid duplication.
=> core: Remove a duplicated declaration of cio_chunk_get_real_size()

tests/context.c
Contrary to the description, passing 5 to `log_level` parameter is
actually valid (which means TRACE level).
We needed to pass an integer larger than 5 to cause cio_create()
to fail.
=> tests: context: CIO_TRACE (5) is a valid debug level

src/CMakeLists.txt, src/cio_os.c
Sophie Fang found that x86 Windows build fails with the following
error:
error LNK2001: unresolved external symbol _SHCreateDirectoryExA
After investigation, it turned out that this was caused by a missing
header file in `cio_os.h`, and can be simply fixed by adding one.
=> cio_os: Fix 'unresolved external symbol _SHCreateDirectoryExA' on x86

src/cio_file_win32.c
The definition was copied verbatim from src/cio_file.c, but it
turned out that the byte order was wrong.
We can confirm this by testing the following with Python:
```python
>>> import binascii, struct
>>> binascii.crc32(b"\0" * 2)
1104745215
>>> struct.pack(">I", 1104745215) # network order
b'A\xd9\x12\xff'
```
So the initial bytes should be the following
```python
{0x41, 0xd9, 0x12, 0xff}
```
not:
```python
{0xff, 0x12, 0xd9, 0x41}
```
Fix the definition thusly.
=> Fix CRC32 in the initialization header

src/cio_file.c
The fallocate operation is failing on e.g. ext3 and reiserf filesystems.
By falling back to use posix_fallocate if the fallocate function call fails
one can keep the performance as is for fallocate supported filesystems but
still support legacy filesystems as ext3 and reiserfs.
This would resolve issue: https://github.com/edsiper/chunkio/issues/46
=> Address issue of falures on ext3 and reiserfs filesystems

include/chunkio/chunkio_compat.h, include/chunkio/cio_file.h, src/cio_chunk.c, src/cio_file.c, src/cio_file_win32.c
Added a function named `cio_file_real_size` that gets the chunk file size of a chunk
regardless of its state and made `cio_chunk_get_real_size` fall back to it if the value
in the structure is zero.
=> chunk file size improvement

src/cio_file_win32.c
This message turns out to be confusing, as Fluent Bit keeps emitting
this message when it hits `max_chunks_up` while processing a large
amount logs.
The same code for Linux/BSD (cio_file.c:497) emits nothing in this
particular failure path. Let's be silent on Windows as well.
=> file: win32: do not emit error messages on 'max_chunks_up'

src/cio_file.c, tests/fs.c
alloc_size may need to reflect the true size of the file here, not the size rounded up. Trying to append to file does not write through when alloc_size misrepresents the true filesize because file resize not detected.
File resize needed on **chunk_down** -> **chunk_up** -> **append** because chunk_down truncates file extra space, chunk_up restores file with alloc_size misrepresenting true filesize (rounded non-truncated filesize) and append expects the file to be non-truncated size and the write fails. 
There are several solution options I tried which all work (the tests fail if none of the following are implemented)
1. Round up only mmap (_implemented_)
- alloc_size not rounded up and represents true file size
- Move `alloc_size = size` above round up. This keeps mmap length still a …
=> file: allocation size adjustment

deps/crc32/crc32.c, include/chunkio/cio_file.h, include/chunkio/cio_file_native.h, include/chunkio/cio_file_st.h, src/CMakeLists.txt, src/cio_file.c, src/cio_file_unix.c, src/cio_file_win32.c, src/cio_memfs.c, src/cio_os.c, src/cio_utils.c, src/win32/dirent.c
These are the key aspects of this PR : 
win32: Implemented a new mapping based system
win32: Refactored the whole module so it only implements a set of primitives used by the file layer
unix: Added a new unix specific file backend that implements a set of standard primitives used by the file layer
utils: Added a recursive deletion function for windows (used by test cases)
Additionally the innermost error type previously reported directly through `cio_errno` has been separated into `cio_file_report_runtime_error` and `cio_file_report_os_error` which report either the `errno` related error for libc issues and the windows specific error (`GetLastError`) for API issues.
Functionality wise this is complete but more test cases should be added before merging in order to ensure that there are no …
=> file: refactored the file layer so it only implements business logic

src/cio_os.c, tests/fs.c
With this fix, out_s3 plugin on macOS starts to create multiparts request bodies correctly.
Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>
=> os: Support cio_os_mkpath correctly on macOS

CMakeLists.txt, include/chunkio/chunkio.h, include/chunkio/cio_chunk.h, include/chunkio/cio_error.h, include/chunkio/cio_file.h, include/chunkio/cio_file_native.h, src/cio_chunk.c, src/cio_error.c, src/cio_file.c, src/cio_file_unix.c, src/cio_file_win32.c, src/cio_scan.c
This PR adds the `CIO_DELETE_IRRECOVERABLE` flag and its dependencies which is used by fluent-bit to delete corrupted chunks that are deemed irrecoverable when they are found.
The two situations upon which a chunk is deemed irrecoverable are magic number corruption and file truncation.
=> corrupted chunk discard patch port

src/cio_file.c
When allocating larger buffers it is still necessary to set the new_size higher than the requested size so the loop needs to be brought back.
```
Thread 2 "flb-pipeline" hit Breakpoint 1, cio_file_write (ch=0x7ffff003c030, buf=0x7ffff5374010, 
count=531440)
at /home/pwhelan/Projects/work/fluent-bit.git/2.1.8/lib/chunkio/src/cio_file.c:927
927	   if (av_size < count) {
(gdb) print av_size
$5 = 4043
(gdb) print count
$6 = 531440
(gdb) next
928	       pre_content = (CIO_FILE_HEADER_MIN + meta_len);
(gdb) 
929	       new_size = cf->alloc_size + cf->realloc_size;
(gdb) 
931	       new_size = ROUND_UP(new_size, ch->ctx->page_size);
(gdb) print new_size
$7 = 528384
(gdb) next
932	       ret = cio_file_resize(cf, new_size);
(gdb) print new_size
$8 = 528384
(gdb) 
```
=> cio_file: fix for SIGSEGV

include/chunkio/cio_file.h, include/chunkio/cio_file_st.h, src/cio_file.c
This PR fixes the faulty logic applied in cio_file_st_get_content_len when handling a chunk that has gone through a filter step that sets the length to a value higher than the systems page size and then back to zero in order to overwrite the data.
Because this is a pure retro compatibility feature we might be able to get rid of it in the future, however, as long as the feature is present this needs to be fixed.
=> file: fixed the content length inference approach

.github/workflows/ci.yaml, src/CMakeLists.txt, src/cio_os.c, src/win32/dirent.c
For Windows Nano Server supporting, we need to replace non existing APIs in Windows Nano Server.
At first, we need to remove the dependencies for PathIsDirectoryA and SHCreateDirectoryEx APIs.
In this PR, avoiding to use PathIsDirectoryA and SHCreateDirectoryEx.
This API is targeted for ordinary Windows platforms.
The full list of supported APIs in Windows Nano Server are:
https://learn.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt588480(v=vs.85)
=> os: dirent: Avoid to use PathIsDirectoryA and SHCreateDirectoryEx for Nano win server
